name: CI

on:
  push:
  pull_request:

permissions: {}

jobs:
  build-and-test:
    name: Lint, Build, Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: extension/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: xvfb-run -a npm run test

      - name: Package VSIX
        run: npx @vscode/vsce package --out turtle-pr-${{ github.run_number }}.vsix

      - name: Upload packaged VSIX artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: turtle-vsix
          path: extension/turtle-pr-${{ github.run_number }}.vsix
          if-no-files-found: error
